apiVersion: v1
kind: Namespace
metadata:
  name: app2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: app2
        image: app2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: TEMPO_ENDPOINT
          value: "http://tempo.monitoring.svc.cluster.local:4318/v1/traces"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
  namespace: app2
  labels:
    app: app2
spec:
  selector:
    app: app2
  ports:
    - port: 8000
      targetPort: 8000
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-traffic-generator
  namespace: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-traffic-generator
  template:
    metadata:
      labels:
        app: app2-traffic-generator
    spec:
      containers:
      - name: traffic-generator
        image: app2-traffic:latest
        imagePullPolicy: Never
        env:
        - name: TARGET_URL
          value: "http://app2-service:8000"
        - name: REQUEST_INTERVAL
          value: "4"
        - name: ERROR_RATE
          value: "0.12"
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"