FROM golang:1.21-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY cmd/traffic-generator/*.go ./
RUN go build -o traffic-generator traffic-generator.go

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /root/

COPY --from=builder /app/traffic-generator .

CMD ["./traffic-generator"]