apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yml: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    limits_config:
      allow_structured_metadata: false

    ruler:
      alertmanager_url: http://alertmanager:9093

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        args:
          - '-config.file=/etc/loki/loki.yml'
        ports:
        - containerPort: 3100
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        volumeMounts:
        - name: loki-config-volume
          mountPath: /etc/loki
        - name: loki-storage-volume
          mountPath: /loki
      securityContext:
        fsGroup: 10001
      volumes:
      - name: loki-config-volume
        configMap:
          name: loki-config
      - name: loki-storage-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  selector:
    app: loki
  type: ClusterIP
  ports:
    - port: 3100
      targetPort: 3100