apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: monitoring
data:
  tempo.yml: |
    server:
      http_listen_port: 3200
      grpc_listen_port: 9095

    distributor:
      receivers:
        jaeger:
          protocols:
            thrift_http:
              endpoint: 0.0.0.0:14268
            grpc:
              endpoint: 0.0.0.0:14250
        zipkin:
          endpoint: 0.0.0.0:9411
        otlp:
          protocols:
            http:
              endpoint: 0.0.0.0:4318
            grpc:
              endpoint: 0.0.0.0:4317
        opencensus:
          endpoint: 0.0.0.0:55678

    ingester:
      max_block_duration: 5m

    compactor:
      compaction:
        compaction_window: 1h
        max_compaction_objects: 1000000
        block_retention: 1h
        compacted_block_retention: 10m

    storage:
      trace:
        backend: local
        block:
          bloom_filter_false_positive: .05
        local:
          path: /tmp/tempo/blocks
        pool:
          max_workers: 100
          queue_depth: 10000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:latest
        args:
          - '-config.file=/etc/tempo/tempo.yml'
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
        ports:
        - containerPort: 3200
        - containerPort: 9095
        - containerPort: 14268
        - containerPort: 14250
        - containerPort: 9411
        - containerPort: 4318
        - containerPort: 4317
        - containerPort: 55678
        volumeMounts:
        - name: tempo-config-volume
          mountPath: /etc/tempo
        - name: tempo-storage-volume
          mountPath: /tmp/tempo
      securityContext:
        fsGroup: 10001
      volumes:
      - name: tempo-config-volume
        configMap:
          name: tempo-config
      - name: tempo-storage-volume
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: monitoring
spec:
  selector:
    app: tempo
  type: NodePort
  ports:
    - name: http
      port: 3200
      targetPort: 3200
      nodePort: 30200
    - name: grpc
      port: 9095
      targetPort: 9095
    - name: jaeger-thrift-http
      port: 14268
      targetPort: 14268
    - name: jaeger-grpc
      port: 14250
      targetPort: 14250
    - name: zipkin
      port: 9411
      targetPort: 9411
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: opencensus
      port: 55678
      targetPort: 55678