---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-parquet-pv
  namespace: monitoring
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: ${NFS_SERVER}
    path: ${NFS_PATH}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-parquet-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs