server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: name
            values: ["monitoring-stack-user-service-1", "monitoring-stack-product-service-1", "monitoring-stack-order-service-1", "monitoring-stack-traffic-generator-1"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: 'monitoring-stack-(.+)-1'
        target_label: 'service'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)' 
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            message: msg
            service: service
            trace_id: trace_id
      - labels:
          service:
          level:
          trace_id:
      - timestamp:
          source: timestamp
          format: RFC3339Nano